ALTER TABLE users
  ADD COLUMN reminder_emails BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN result_emails BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN terms_version VARCHAR(30) NULL,
  ADD COLUMN terms_accepted_at DATETIME(3) NULL;

CREATE TABLE support_requests (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  category VARCHAR(30) NOT NULL,
  message TEXT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'open',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  resolved_at DATETIME(3) NULL,
  CONSTRAINT support_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
